
FIND_PATH(SYSTEMD_INCLUDE_DIR
  NAMES sd-daemon.h
  PATH_SUFFIXES include/ systemd/
  PATHS "${PROJECT_SOURCE_DIR}/../systemd/"
  ${SYSTEMD_ROOT}
  $ENV{SYSTEMD_ROOT}
  /usr/include/
  /usr/local/
  /usr/
)

IF(SYSTEMD_INCLUDE_DIR)
  SET(SYSTEMD_FOUND TRUE)
ELSE(SYSTEMD_INCLUDE_DIR)
  SET(SYSTEMD_FOUND FALSE)
ENDIF(SYSTEMD_INCLUDE_DIR)

IF(SYSTEMD_FOUND)
  MESSAGE(STATUS "Found Systemd in ${SYSTEMD_INCLUDE_DIR}")
ELSE(SYSTEMD_FOUND)
  IF(SYSTEMD_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find Systemd library")
  ENDIF(SYSTEMD_FIND_REQUIRED)
ENDIF(SYSTEMD_FOUND)

MARK_AS_ADVANCED(
  SYSTEMD_INCLUDE_DIR
)

