
MARK_AS_ADVANCED( PROJECT_DEFAULT_USER )
    IF(NOT PROJECT_DEFAULT_USER)
        SET(PROJECT_DEFAULT_USER  "nobody")
    ENDIF(NOT PROJECT_DEFAULT_USER)

MARK_AS_ADVANCED( PROJECT_DEFAULT_GROUP )
    IF(NOT PROJECT_DEFAULT_GROUP)
        SET(PROJECT_DEFAULT_GROUP "nogroup")
    ENDIF(NOT PROJECT_DEFAULT_GROUP)

MARK_AS_ADVANCED( PROJECT_SYSCONF_DIR )
    IF(NOT PROJECT_SYSCONF_DIR)
        SET(PROJECT_SYSCONF_DIR ${SYSCONF_INSTALL_DIR}/pdns-logger/)
    ENDIF(NOT PROJECT_SYSCONF_DIR)

MARK_AS_ADVANCED( PROJECT_STATE_DIR )
    IF(NOT PROJECT_STATE_DIR)
        SET(PROJECT_STATE_DIR ${CMAKE_INSTALL_PREFIX}/run/)
    ENDIF(NOT PROJECT_STATE_DIR)

MARK_AS_ADVANCED( PROJECT_LOG_DIR )
    IF(NOT PROJECT_LOG_DIR)
        SET(PROJECT_LOG_DIR ${CMAKE_INSTALL_PREFIX}/var/log/pdns-logger)
    ENDIF(NOT PROJECT_LOG_DIR)

MARK_AS_ADVANCED( PROJECT_MODULES_DIR )
    IF(NOT PROJECT_MODULES_DIR)
        SET(PROJECT_MODULES_DIR ${LIB_INSTALL_DIR}/pdns-logger/modules)
    ENDIF(NOT PROJECT_MODULES_DIR)

#MARK_AS_ADVANCED( PROJECT_LANG_DIR )
#    IF(NOT PROJECT_LANG_DIR)
#        SET(PROJECT_LANG_DIR ${CMAKE_INSTALL_PREFIX}/lib/name/lang)
#    ENDIF(NOT PROJECT_LANG_DIR)
